### PR TITLE
kodi: added vaapi and vdpau support.

### PR DESCRIPTION
**Pull request by dev-0x7C6**
I have positive logs from kodi that vaapi library is loaded correctly. Seems that vaapi is preferred video acceleration method - mesa is shipping multiple drivers compatible with vaapi.

Added:
**VAAPISUPPORT** is on when opengl flag is set in **DISTRO_FEATURES** (this is based on libva restrictions)

**VDPAUSUPPORT** is on when x11 flag is set in **DISTRO_FEATURES** (this is based on libvdpau restrictions)

Removed:
**KODIACCELERATIONLIBRARIESX86DEFAULTS**, **KODIADDITIONALCODECS**.

**KODIGRAPHICALBACKEND** choice is now filtered by supported flags.

### CODE REVIEW

**Comment by dev-0x7C6** [comment]
After this PR, I'll create zeus branch from devel.

**Comment by dev-0x7C6** [comment]
> wayland needs libwaylandpp, which we doesn’t build

By fast grepping, kodi is only recipe that using waylandpp which is not existent (libwaylandpp also). I'll compile wayland version and I'll check configure log for missing deps, probably there is more.

> like amlogic, the rpi backend should be avoided, gbm is a much better fit for that

Ok, I'll filter only for **gbm**, **wayland** and **x11**. Should I also remove **PACKAGECONFIG** options for amlogic and raspberrypi?

> Mesa shouldn’t inherit kodi classes

Should I go for another class (*video-acceleration-support.bbclass*) ?  **VAAPISUPPORT** and **VDPAUSUPPORT** is used in kodi, ffmpeg and mesa recipes/overrides. Or just copy those for each recipe (It'll end up harder/misleading to maintain, because of copied if statements (*bb.utils.contains*), and can end-up with different defaults for each if someone is not aware).

**Comment by koenkooi** [comment]
> > wayland needs libwaylandpp, which we doesn’t build
> 
> By fast grepping, kodi is only recipe that using waylandpp which is not existent (libwaylandpp also). I'll compile wayland version and I'll check configure log for missing deps, probably there is more.

LIbwaylandpp will need similar magic to what OE-core has for wayland-scanner, I couldn't get it to work, so good luck :)
 
> > like amlogic, the rpi backend should be avoided, gbm is a much better fit for that
> 
> Ok, I'll filter only for **gbm**, **wayland** and **x11**. Should I also remove **PACKAGECONFIG** options for amlogic and raspberrypi?

Yes, please remove those.
 
> > Mesa shouldn’t inherit kodi classes
> 
> Should I go for another class (_video-acceleration-support.bbclass_) ? **VAAPISUPPORT** and **VDPAUSUPPORT** is used in kodi, ffmpeg and mesa recipes/overrides. Or just copy those for each recipe (It'll end up harder/misleading to maintain, because of copied if statements (_bb.utils.contains_), and can end-up with different defaults for each if someone is not aware).

A seperate class would be nice, I'd call it vpu.bbclass or something like that, earlier bitbake versions didn't handle multiple '-' in class names very well.

**Comment by dev-0x7C6** [comment]
> LIbwaylandpp will need similar magic to what OE-core has for wayland-scanner, I couldn't get it to work, so good luck :)

I'll probably deliver it in another PR if I manage to resolve that. I'll postpone merge to zeus branch for now.

> A seperate class would be nice, I'd call it vpu.bbclass or something like that, earlier bitbake versions didn't handle multiple '-' in class names very well.

Short version is also appealing. Probably isn't sane to run latest branches with old bitbake versions. Right now this layer depends on zeus branches from OE - there is probably more stuff to fail due old bitbake. Just saying ;-)

We have also kodi-common.bbclass and kodi-addons.bbclass, should I rename them to kodicommon.bbclass and kodiaddons.bbclass ?

**Comment by dev-0x7C6** [comment]
@koenkooi  I was able to compile **waylandpp** and **kodi** with wayland support after changes introduced in 5037f90 (not tested in runtime yet)

Changes that I introduced in **pugixml** probably should go to upstream OE
*recipes-devtools/pugixml/pugixml_%.bbappend*

I'm not sure about *wayland_%.bbappend*, but probably this is a use case that depends on wayland libraries in native context.

There is a room to improve **waylandpp** recipe, but I think it's good start.

What do you think? Should I send patches to OE and propose **waylandpp** as new recipe?

**Comment by koenkooi** [comment]
It would be less work for meta-kodi in the long run if the wayland bits are upstream in oe-core.

**Comment by dev-0x7C6** [comment]
Closing in favor of #26

**Pull request closed without merging**
