### PR TITLE
addons: updated inputstream.adaptive and pvr.hts, minor variable renaming.

### PR DESCRIPTION
**Pull request by dev-0x7C6**
Updates:
* **kodi-addon-inputstream-adaptive** from 2.3.11 to **2.4.3**
**kodi-addon-pvr-hts** from 4.4.3 to **4.4.20**

Introduced:
* **KODI_CODENAME** -  which is used across kodi, kodi-tools-* and kodi-addons-* recipes. This was previously named **CODENAME** but I think it's to short and may collide with something else. Many plugins and kodi itself using versioning tags like "${PV}-${KODI_CODENAME}", I think it's good idea to not hardcode ${PV}-Leia in every of them - it'll be easier to migrate to upcoming Matrix release that way. By changing **KODI_CODENAME** to Matrix bitbake will fail on addons and other parts that needs to be updated. (Addons have different versions for Matrix, this is true at least for inputstream.adaptive and pvr.hts)

* **KODI_ADDON_DIR** which is used across kodi-addons-* (and kodi in future) in order to set same path across modules.

Renamed:
* **KODIADDONNAME** to **KODI_ADDON_NAME** - easier to read
* **DEFAULT_KODI_URI** to **KODI_URI** - I just dropped DEFAULT_ part to have shorter name, used by kodi and kodi-tools-*
* **DEFAULT_KODI_REV** to **KODI_REV** - same here
* **DEFAULT_KODI_WORKDIR** to **KODI_WORKDIR** - used by kodi-tools-*, they have different project path

Additional note:
I spotted that some forked repositories of meta-kodi using different URI, this maybe for development, testing or customizing reason. So I introduced **DEFAULT_KODI_URI** and **DEFAULT_KODI_REV** in my previous commits. This may help someone to customize URI, but I'm not strongly holding to this idea, we may also drop it if this is overkill.

I successfully build kodi **(gbm)** for intel-corei7-64, intel-core2-32, raspberrypi3, raspberrypi4, raspberrypi4-64. I tested video playback on intel-corei7-64, raspberrypi4 and it's working :-) I got strange video-tearing on rpi4 but I found that is common problem on rpi4 right now (something with drivers and unstable vsync) - so probably nothing to fix in kodi itself.

### CODE REVIEW

**Comment by koenkooi** [comment]
_ is used in OE as an operator to separate overrides, which is why it should be avoided in variable names.

**Comment by dev-0x7C6** [comment]
All overrides that I had seen was lower case coded. There is a great amount of variables provided by meta-oe and other layers that looks like FOO_BAR or FOO_BAR_FOO.

Is common practice to use overrides with lower case rather than avoid FOO_BAR? I never tested if overrides even work with upper cases (OVERRIDES += "BAR"), maybe this is even QA validation.

I ask about KODI_ADDON_NAME and KODI_CODE_NAME naming on #yocto channel, and they give me answer that underscores are used in lots of variable names already.

Should I remove underscores from those variables? I personally think the better approach is to have easier to read variables names than avoid overriding operator at any cost.

**Comment by dev-0x7C6** [comment]
I made interesting test, I added those line to x265 recipe:

OVERRIDES_append = ":addon:URI:ADDON"

KODI_TEST_ADDON = "FOO"
KODI_addon = "BAR"

And output of MACHINE="intel-corei7-64" bitbake x265 -e | grep ^KODI

KODI="BAR"
KODI_TEST_ADDON="FOO"
KODI_addon="BAR"

Override operator _ is not working for upper case variables. SRC_URI was also not affected by override.

Update: I changed KODI_ADDON to KODI_TEST_ADDON to correct test case.

**Comment by koenkooi** [comment]
It's generally not used in variable names to avoid confusion. The bitbake feature that it will ignore uppercase is something new, it didn't use to do that. I still think using an operator in variable names is bad form. A lot of the variables in oe-core have an underscore in them because we didn't realize the implications at the time, since as you mentioned, they make it easier to read.

**Comment by dev-0x7C6** [comment]
> It's generally not used in variable names to avoid confusion. The bitbake feature that it will ignore uppercase is something new, it didn't use to do that. I still think using an operator in variable names is bad form. A lot of the variables in oe-core have an underscore in them because we didn't realize the implications at the time, since as you mentioned, they make it easier to read.

I consider underscore character as operator a bad design choice if you ask me. Underscore is commonly used in variable naming conventions across many languages, and may new developers (count me in) is confused by this by great amount :-). After countless uses of FOO_x86 = "xyz" I have come to like it, but underscore should be replaced (in early days of design) by something else.

Should I remove underscores from those variables? What is your decision.

**Comment by koenkooi** [comment]
For existing variables: leave underscores in, don't add them. For new variables: avoid underscores.

And yes, the underscore is unfortunate, I think you can go back 15 years and look at #oe IRC logs where people point that out :)

**Comment by dev-0x7C6** [comment]
> For existing variables: leave underscores in, don't add them. For new variables: avoid underscores.

You mean don't remove them yes? I don't like if statements in code and in rules :-) I will rather convert all to one convention to reduce confusion (I'm okay with converting all to one standard even if it's extra work for me). If we'll leave it half underscored and half not. The new developers that may show up in future. Will blame (quietly) me or you to be not consistent or just ship patches FOO_BAR or FOOBAR at random. 

If decision is avoid underscores for new variables, I'll take extra work to convert old ones to match that, is that ok?

We can add guidelines for variable naming in extra file like guidelines.md. This file may be handy in case if someone will introduce underscore in variables in PR.

**Comment by koenkooi** [comment]
Removing them is OK by me, but we can't get them all, since not all upstream variables follow the convention :(

**Comment by dev-0x7C6** [comment]
@koenkooi  Please check e2612f7 and merge PR if this is fine.

**Pull request merged**
