### PR TITLE
Major recipes refactoring, zeus support with latest versions.

### PR DESCRIPTION
**Pull request by dev-0x7C6**
Hi,

I'm working on kodi stuff lately. I don't want to diverse from your repository as some repository already doing. Are you still interested in maintaining (accept PRs) official kodi layer? I can lend a hand and work on support for zeus and later releases. I'm working on my own distribution that's focusing on retro games emulation and I want also have strong media center on it, so I'm motivated ;-)

I'll un-wip PR when things will be ready and somewhat tested. I'm not sure about some changes at this point. I changed formatting slightly (using guidelines from Yocto), hope it's not a problem.

Happy 3D printing ;-),
Bartłomiej

### CODE REVIEW

**Comment by koenkooi** [comment]
That’s good to hear! I was talking about this with Scott earlier this week and we thought zeus should have its own branch, what are your thoughts on that?

**Comment by dev-0x7C6** [comment]
Yes, zeus should have it's own branch. I just targeted warrior at this point because I was unable to PR to non-existent branch.

**Comment by koenkooi** [comment]
You have write access now, so feel free to create the branch yourself :) I'll start doing my own changes as PRs from now on as well.

**Comment by g-scott-murray** [comment]
I've got a tree locally where I've been building against zeus, there's a handful of other recipes that can be cleaned out.  I'll put something up as a zeus branch this weekend if it's not been created already.

**Comment by dev-0x7C6** [comment]
@koenkooi Thanks for privileges :-) I'm wondering about merge it firstly to "devel"/"zeus-devel" branch (or rebase it to master?), since zeus branch should contain tested and stable stuff. This way we'll not end with huge PR and users will be not exposed to in-development-zeus branch scenario.

@g-scott-murray We'll probably end-up with conflicts then, can you show those changes? Maybe I'll able to cherry-pick something early-on. Not sure about your progress there, maybe I'm behind :-) Just in case if you have only changes to make kodi work with zeus, maybe it's good idea to make zeus branch only from your changes and apply my refactoring later on.

**Comment by dev-0x7C6** [comment]
I was able to build wic image for intel-corei7-64 machine, successfully booting to kodi from pendrive. Video and audio working, fluid animation on i7-4600u. Playback works well, but without hw acceleration. Kodi splash screen appeared a little late, console login was visible for 10s after that splash showed up just for 1-2s - but maybe this quirk is related to my pendrive bandwidth.

Update: booting on PC using usb 3.0 port, kodi loading from pen-drive without delay.

I need to fix mesa bbappend that I removed temporarily and provide proper libvdpau / vaapi. I'm also working on meta-glvnd which using libglvnd to route opengl/es calls to proper rendering backend, this also using bbappend on mesa, so I need to workout seamless approach.

Later today I'll try to build and test for raspberrypi3 and raspberrypi4 with opensource graphical stack, maybe I'll check also raspberrypi4-64.

**Comment by koenkooi** [comment]
A devel branch makes sense, go for it.

**Pull request merged**
