### PR TITLE
Master next

### PR DESCRIPTION
**Pull request by MarkusVolk**
rebased to master-next

### CODE REVIEW

**Comment by dev-0x7C6** [comment]
Thanks! I'm glad that you managed to remove old `crossguid`.

**Comment by dev-0x7C6** [comment]
I'll rebase those changes shortly after build/runtime tests.

**Comment by MarkusVolk** [comment]
This has been annoying for years. I dont understand why one needs to replace guid with Guid or .h with .hpp ... unless you are writing new Code.
I have seen that latest crossguid commits add packageconfig support. Perhaps the patch on kodi won't be needed anymore if updating crossguid. But in my opinion its always better to stick with the recipes provided by meta-oe ... as long as possible

**Comment by MarkusVolk** [comment]
> I'll rebase those changes shortly after build/runtime tests.

you might also remove the fmt recipe from hardknott branch. Its already gone in master-next, so this patch is missing here

**Comment by dev-0x7C6** [comment]
I was able successfully build kodi. `master` and `hardknott` now contains all commits from `master-next`.

**Pull request merged**
